### ISSUE TITLE
Does this library cause a crash report? JSApplicationIllegalArgumentException

### ISSUE THREAD

**Issue by jordangrant** [avishayil/react-native-restart#144]
Does this cause a crash to be reported to Crashlytics?
I went through my diff of when I started noticing the following issue in Production coinciding with the addition of this library.

```
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException
Error while updating property 'flex' in shadow node of type: RCTView
```

I was hoping it was a false report and due to a sudden restart upon app launch.

I'm going to remove it for a couple days, as a test, and see.

**Comment by jordangrant** [comment]
<img width="1257" alt="Screen Shot 2020-11-14 at 9 44 42 AM" src="https://user-images.githubusercontent.com/7986493/99149769-1372bd00-265e-11eb-907f-bf637b291e1e.png">

**Comment by jordangrant** [comment]
I can pretty confidently say in my case this issue was caused by calling RNRestart.restart() soon after app launch and producing crash reports

```
Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'justifyContent' in shadow node of type: RCTView
       at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:125)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:161)
       at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:65)
       at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:320)
       at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:251)
       at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:469)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:154)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by kuldeepworkid** [comment]
App is running perfectly but when i click on a button which contains **RNRestart.Restart();** its crashes by giving the above error
