### ISSUE TITLE
App crashes after calling RNRestart.Restart() in webview. App is running fine but when is call RNRestart.Restart() in webview on url change then its causes crashes in release build in some android phone (redmi, samsung)

### ISSUE THREAD

**Issue by kuldeepworkid** [avishayil/react-native-restart#172]
2021-07-05 18:29:46.971 22990-24054/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.app.packageName, PID: 22990
    com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'collapsable' in shadow node of type: RCTView
        at com.facebook.react.uimanager.b1$k.a(Unknown Source:113)
        at com.facebook.react.uimanager.z0$b.a(Unknown Source:10)
        at com.facebook.react.uimanager.z0.a(Unknown Source:36)
        at com.facebook.react.uimanager.b0.a(Unknown Source:0)
        at com.facebook.react.uimanager.o0.a(Unknown Source:71)
        at com.facebook.react.uimanager.UIManagerModule.createView(Unknown Source:53)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:149)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
        at android.os.Looper.loop(Looper.java:236)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.IllegalArgumentException: method com.facebook.react.uimanager.i.setCollapsable argument 1 has type boolean, got java.lang.Float
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.b1$k.a(Unknown Source:18)
        at com.facebook.react.uimanager.z0$b.a(Unknown Source:10) 
        at com.facebook.react.uimanager.z0.a(Unknown Source:36) 
        at com.facebook.react.uimanager.b0.a(Unknown Source:0) 
        at com.facebook.react.uimanager.o0.a(Unknown Source:71) 
        at com.facebook.react.uimanager.UIManagerModule.createView(Unknown Source:53) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:149) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0) 
        at android.os.Looper.loop(Looper.java:236) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37) 
        at java.lang.Thread.run(Thread.java:923) 
2021-07-05 18:29:46.975 22990-24054/? D/OOMEventManagerFK: checkEventAndDumpForJE: 0
2021-07-05 18:29:46.989 1436-24081/? I/DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2

**Comment by syneinsindia** [comment]
Same issue

**Comment by avishayil** [comment]
Hi, I currently have no means to replicate this issue. Don't have a Samsung or Redmi phone. I am optimistic since #211 implements a new restart mechanism, so please report back after updating to 0.0.25.
