### ISSUE TITLE
app crash on press Restart

### ISSUE THREAD

**Issue by ferasabufares** [avishayil/react-native-restart#200]
can you help me please my app crash without any error after run  RNRestart.Restart()

platform :Android

```
     await AsyncStorage.removeItem('user_id');
     await AsyncStorage.removeItem('access_token');
           setTimeout(() => {
            RNRestart.Restart();
           }, 500);
```

```
   "@ilterugur/react-native-deck-swiper-renewed": "^2.1.7",
    "@invertase/react-native-apple-authentication": "^2.1.5",
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.16.1",
    "@react-native-community/blur": "^3.6.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-community/netinfo": "^8.0.0",
    "@react-native-community/push-notification-ios": "^1.10.1",
    "@react-native-community/slider": "^4.2.0",
    "@react-native-firebase/analytics": "^14.4.0",
    "@react-native-firebase/app": "^14.4.0",
    "@react-native-firebase/database": "^14.7.0",
    "@react-native-firebase/dynamic-links": "^14.4.0",
    "@react-native-firebase/in-app-messaging": "^14.7.0",
    "@react-native-firebase/messaging": "^14.4.0",
    "@react-native-google-signin/google-signin": "^7.0.4",
    "@react-navigation/native": "^6.0.8",
    "@react-navigation/stack": "^6.1.1",
    "@trava/react-native-drax": "^0.9.8",
    "@yz1311/react-native-intent-launcher": "^0.3.3",
    "appcenter": "4.4.3",
    "appcenter-analytics": "4.4.3",
    "appcenter-crashes": "4.4.3",
    "moment": "^2.29.1",
    "native-base": "^3.3.6",
    "react": "17.0.1",
    "react-native": "0.64.1",
    "react-native-animatable": "^1.3.3",
    "react-native-app-intro-slider": "^4.0.4",
    "react-native-audio-recorder-player": "^3.3.4",
    "react-native-awesome-alerts": "^1.5.2",
    "react-native-camera": "^4.2.1",
    "react-native-card-stack-swiper": "^1.2.5",
    "react-native-code-push": "^7.0.4",
    "react-native-confirmation-code-field": "^7.3.0",
    "react-native-countdown-component": "^2.7.1",
    "react-native-date-picker": "^4.1.5",
    "react-native-detect-navbar-android": "^0.3.0",
    "react-native-device-info": "^8.4.9",
    "react-native-drax": "^0.9.3",
    "react-native-fast-image": "^8.5.11",
    "react-native-fbsdk-next": "^4.6.0",
    "react-native-fs": "^2.18.0",
    "react-native-geocoding": "^0.5.0",
    "react-native-geolocation-service": "^5.3.0-beta.4",
    "react-native-gesture-handler": "^2.3.1",
    "react-native-gifted-chat": "^0.16.3",
    "react-native-google-maps-directions": "^2.1.1",
    "react-native-google-places-autocomplete": "^2.4.1",
    "react-native-image-picker": "^4.7.3",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-maps": "^0.30.1",
    "react-native-permissions": "^3.3.1",
    "react-native-push-notification": "^8.1.1",
    "react-native-reanimated": "^2.4.1",
    "react-native-render-html": "^6.3.4",
    "react-native-restart": "0.0.24",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-safe-area-view": "^1.1.1",
    "react-native-screens": "~3.10.2",
    "react-native-sectioned-multi-select": "^0.9.1",
    "react-native-skeleton-content-nonexpo": "^1.0.13",
    "react-native-status-bar-height": "^2.6.0",
    "react-native-svg": "^12.1.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-video": "^5.2.0",
    "react-native-view-shot": "^3.1.2",
    "react-native-webview": "^11.17.2",
    "react-redux": "^7.2.6",
    "redux": "^4.1.2",
    "rn-fetch-blob": "^0.12.0",
    "rn-swipe-button": "^1.3.6"
```

**Comment by haresh4d** [comment]
Same problem in iOS too.

**Comment by HammzaHM** [comment]
This is an android specific issue I've made a [PR](https://github.com/avishayil/react-native-restart/pull/211).

**Comment by Nikola-Andreev** [comment]
Any plans to release that soon?

**Comment by ptfly** [comment]
Yeah, will be much appreciated if that PR gets merged and released.

**Comment by avishayil** [comment]
Merged. Please report if it comes back.

**Comment by nguyenduythuc** [comment]
Still crash app on emulator pixel 2 API 31, React Native 0.71.1

`import RNRestart from 'react-native-restart';
...
<View>
  <Text>Something happened!</Text>
  {/* <Text>{props.error.toString()}</Text> */}
  <Button onPress={() => RNRestart.restart()}>click</Button>
</View>`

**Comment by yberstad** [comment]
Hi, I'm experiencing the same issue. 
I'm using 0.72.0-RC.5. It works fine with 0.0.24, but using 0.0.27 the app crashes when calling RNRestart.Restart() with the following exception:

```
--------- beginning of crash
06-08 12:30:08.329 17586 17586 E AndroidRuntime: FATAL EXCEPTION: main
06-08 12:30:08.329 17586 17586 E AndroidRuntime: Process: com.appname.dev:phoenix, PID: 17586
06-08 12:30:08.329 17586 17586 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.appname.MainApplication: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.appname.dev:phoenix (pid 17586), lock owner com.appname.dev (pid 17346)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6996)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2235)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8170)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.appname.dev:phoenix (pid 17586), lock owner com.appname.dev (pid 17346)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle.apk-stable-567252433:187)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at org.chromium.android_webview.AwBrowserProcess.k(chromium-TrichromeWebViewGoogle.apk-stable-567252433:15)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at com.android.webview.chromium.M.d(chromium-TrichromeWebViewGoogle.apk-stable-567252433:180)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at com.android.webview.chromium.M.b(chromium-TrichromeWebViewGoogle.apk-stable-567252433:173)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(chromium-TrichromeWebViewGoogle.apk-stable-567252433:16)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at android.webkit.WebView.setWebContentsDebuggingEnabled(WebView.java:2020)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at com.appname.MainApplication.onCreate(MainApplication.java:72)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6991)
06-08 12:30:08.329 17586 17586 E AndroidRuntime: 	... 9 more
```

**Comment by jensdev** [comment]
Any update on this? 
I'm facing the same issue.
```
FATAL EXCEPTION: main

Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.myapp:phoenix (pid 10330), lock owner com.myapp (pid 9078)
```
