### ISSUE TITLE
Showing a white screen with RNRestart.Restart().

### ISSUE THREAD

**Issue by saadi-ninjasCode** [avishayil/react-native-restart#233]
First of all sorry to recreate the issue, All previously related issues are closed and their solutions are not acceptable anymore because of the latest version of React-Native.

### **Problem:** 
 There is a white screen when we call  `RNRestart.Restart()`. 

-  **Previous Solution**
Show the splash screen when calling `RNRestart.Restart()` #194 , #158 

In the above Solution, people mention the library `react-native-splash-screen`, which is no longer maintained. While there is another up-to-date library [react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash), Previously library has support to show the splash screen (Once splash screen hides). 

####  **New Issue**
[react-native-bootsplash](https://github.com/zoontek/react-native-bootsplash) removed support to show the splash screen (Once splash screen hides) in latest version when giving support for Android 12. 
-**Reason**: [Can't be possible with AndroidX core splash screen module](https://github.com/zoontek/react-native-bootsplash/issues/401#issuecomment-1307972722) and https://github.com/zoontek/react-native-bootsplash/issues/354#issuecomment-1130346424

#### Solution
_Any help would be greatly appreciated._

**Comment by avishayil** [comment]
Thanks @saadi-ninjasCode for the detailed issue. Could you please help me in some detailed step in how to replicate the issue?

**Comment by saadi-ninjasCode** [comment]
> Thanks @saadi-ninjasCode for the detailed issue. Could you please help me in some detailed step in how to replicate the issue?

Yeah Sure, 
First of all, You can create a simple RN project and add a button on the screen. On pressing button call the restart function from `react-native-restart`. You will see a blank white/black (Dependent on mobile theme). 
I will provide the Expo Snack for you. But I'm little bit busy now.

**Comment by avishayil** [comment]
> > Thanks @saadi-ninjasCode for the detailed issue. Could you please help me in some detailed step in how to replicate the issue?
> 
> Yeah Sure, First of all, You can create a simple RN project and add a button on the screen. On pressing button call the restart function from `react-native-restart`. You will see a blank white/black (Dependent on mobile theme). I will provide the Expo Snack for you. But I'm little bit busy now.

Just to understand, like in the gif that is shown on the README, until the app is restarted, white screen is shown?
What would be the expected behavior in your mind?

**Comment by saadi-ninjasCode** [comment]
> > > Thanks @saadi-ninjasCode for the detailed issue. Could you please help me in some detailed step in how to replicate the issue?
> > 
> > 
> > Yeah Sure, First of all, You can create a simple RN project and add a button on the screen. On pressing button call the restart function from `react-native-restart`. You will see a blank white/black (Dependent on mobile theme). I will provide the Expo Snack for you. But I'm little bit busy now.
> 
> Just to understand, like in the gif that is shown on the README, until the app is restarted, white screen is shown? What would be the expected behavior in your mind?

In my opinion, there should be a splash screen or the icon of an app in the center of the screen (As Android 12 allows only a icon now). [Android 12 Splash Screen](https://developer.android.com/develop/ui/views/launch/splash-screen#elements)

**Comment by sai20459** [comment]
**_VERSION =0.027_**
```
> Task :react-native-restart:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
115 actionable tasks: 5 executed, 110 up-to-date

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-restart:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-restart:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /home/naveen/Android/Sdk/platforms/android-33/core-for-system-modules.jar.
         > jlink executable /usr/lib/jvm/java-18-openjdk-amd64/bin/jlink does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 35s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-restart:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-restart:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /home/naveen/Android/Sdk/platforms/android-33/core-for-system-modules.jar.
         > jlink executable /usr/lib/jvm/java-18-openjdk-amd64/bin/jlink does not exist.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 35s

    at makeError (.../node_modules/execa/index.js:174:9)
    at .../node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (../node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (../node_modules/@react-native-community/cli/build/index.js:108:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
---
Package is working fine with **_VERSION=0.0.24_**

**Comment by umerhayat54** [comment]
any lucky anyone?

**Comment by Kailash-dev** [comment]
any update related to this ??

**Comment by Ozaoujal** [comment]
same issue here!

**Comment by asadalihazoori** [comment]
i am also facing this issue

**Comment by art9mid** [comment]
same issue

**Comment by elabayoub** [comment]
Try enabling hermes.

**Comment by Leslie-Wong-H** [comment]
The same issue occurred on certain android 13 and android 15 devices from our tests. Adopting and wrapping the java codes found here as a react native module helps resolving it.

https://github.com/oncealong/restartApp/blob/master/app/src/main/java/com/wang/along/restartapp/RestartApp.java

**Comment by loijwdev** [comment]
any update

**Comment by avishayil** [comment]
This is a duplicate of #238 where we're tracking the splash screen / white screen issue during restart.

The issue stems from:
- react-native-bootsplash can't re-show after Android 12
- Platform restrictions on showing persistent screens during app restart
- The brief gap between process termination and restart

See #238 for discussion and potential workarounds.

Closing as duplicate. Please continue discussion in #238.

**Comment by ChadyAyoub4** [comment]
White screen is due to the root layer of the application being white, this is not an issue with this package. You can fix this by setting the root application background color to your app theme color from the native side Android + Ios
For Android in styles.xml add this line <item name="android:windowBackground">#000000 or your app color</item>
For Ios add this line in your appdelegate.swift (if you are on a newer RN version, for older version it's similar but different syntax) in fun application before the return add this
 if let rootViewController = window?.rootViewController {
      rootViewController.view.backgroundColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.0) // black or your them color
    }
