### ISSUE TITLE
android app crashed

### ISSUE THREAD

**Issue by nhhynd** [avishayil/react-native-restart#268]
when i called RNResatrt.restart(), app crashed.

**crash report**

FATAL EXCEPTION: main

Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.kakaobank.watchtower.meerkat.dev:phoenix (pid 5519), lock owner com.kakaobank.watchtower.meerkat.dev (pid 4944)

FATAL EXCEPTION: main
Process: com.kakaobank.watchtower.meerkat.dev:phoenix, PID: 5519
java.lang.RuntimeException: Unable to create application com.kakaobank.watchtower.meerkat.MainApplication: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.kakaobank.watchtower.meerkat.dev:phoenix (pid 5519), lock owner com.kakaobank.watchtower.meerkat.dev (pid 4944)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7672)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2410)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**react native info**
System:
  OS: macOS 14.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 13.83 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.22
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.03.25.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.11005911
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by timorss** [comment]
what are u running berfore u run the restart?

try to put await of 1 second before

**Comment by nhhynd** [comment]
@timorss 

i didn't run something before restart.
i tried to put await of 1 second
but app crashed still

**Comment by nhhynd** [comment]
i resolved this issue.

reason:
```
@Override
  public void onCreate() {
    super.onCreate();

    // for react-native-webview debugging
    WebView.setWebContentsDebuggingEnabled(true);
```
