### ISSUE TITLE
Crash on android when restarting

### ISSUE THREAD

**Issue by shakedOno** [avishayil/react-native-restart#41]
Getting a crash on android, iOS works fine. Using RN version 0.55.4.
Having trouble fixing this. Any ideas?
Thanks

Logs:
E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.matific, PID: 28069
                                                             java.lang.RuntimeException: com.facebook.react.uimanager.IllegalViewOperationException: Trying to remove a view index above child count 1 view tag: 11
                                                              detail: View tag:-1
                                                               children(0): [
                                                              ],
                                                               indicesToRemove(1): [
                                                             1,
                                                              ],
                                                               tagsToDelete(1): [
                                                             670,
                                                              ]
                                                             
                                                                 at com.facebook.react.bridge.ReactContext.handleException(ReactContext.java:311)
                                                                 at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:23)
                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
                                                              Caused by: com.facebook.react.uimanager.IllegalViewOperationException: Trying to remove a view index above child count 1 view tag: 11
                                                              detail: View tag:-1
                                                               children(0): [
                                                              ],
                                                               indicesToRemove(1): [
                                                             1,
                                                              ],
                                                               tagsToDelete(1): [
                                                             670,
                                                              ]
                                                             
                                                                 at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:351)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:179)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:821)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:928)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue.access$2100(UIViewOperationQueue.java:46)
                                                                 at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:886)
                                                                 at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:21)
                                                                 	... 7 more

**Comment by shakedOno** [comment]
I managed to find the issue. 
The function that was calling the restart was called with await.
So something like this:

const restartApp = async () => {
  //Code that needs await
  
  RNRestart.Restart();
}

const callingMethod = async () => {
  //Some random code

  **await** restartApp()
}

Once the await in bold was removed everything worked.

**Comment by avishayil** [comment]
Glad you sorted that out!
